/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health check */
        get: operations["health"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/sign-in": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Sign in with email and password */
        post: operations["signIn"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/refresh": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Rotate access token using refresh token */
        post: operations["refreshToken"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/sync/pull": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Pull delta changes from server */
        get: operations["syncPull"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/sync/push": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Push local changes to server */
        post: operations["syncPush"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/photos/upload-url": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Get pre-signed PUT URL for photo upload */
        post: operations["getPhotoUploadUrl"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        HealthResponse: {
            /** @example ok */
            status: string;
        };
        SignInRequest: {
            /** Format: email */
            email: string;
            password: string;
        };
        RefreshRequest: {
            refreshToken: string;
        };
        TokenPair: {
            accessToken: string;
            refreshToken: string;
        };
        /** @enum {string} */
        EntityType: "project" | "plan" | "photo";
        /** @enum {string} */
        OpType: "create" | "update" | "delete";
        ProjectPayload: {
            name: string;
            description?: string | null;
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            entityType: "project";
        };
        PlanPayload: {
            /** Format: uuid */
            projectId: string;
            name: string;
            description?: string | null;
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            entityType: "plan";
        };
        PhotoPayload: {
            /** Format: uuid */
            planId: string;
            contentType: string;
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            entityType: "photo";
        };
        EntitySnapshot: {
            entityType: components["schemas"]["EntityType"];
            /** Format: uuid */
            entityId: string;
            payload: components["schemas"]["ProjectPayload"] | components["schemas"]["PlanPayload"] | components["schemas"]["PhotoPayload"];
        };
        PushOperation: {
            /** Format: uuid */
            clientOpId: string;
            op: components["schemas"]["OpType"];
            entityType: components["schemas"]["EntityType"];
            /** Format: uuid */
            entityId: string;
            /**
             * Format: int64
             * @description Client-side timestamp in epoch milliseconds
             */
            clientUpdatedAt: number;
            payload: components["schemas"]["ProjectPayload"] | components["schemas"]["PlanPayload"] | components["schemas"]["PhotoPayload"];
        };
        PullChange: {
            entityType: components["schemas"]["EntityType"];
            /** Format: uuid */
            entityId: string;
            payload: components["schemas"]["ProjectPayload"] | components["schemas"]["PlanPayload"] | components["schemas"]["PhotoPayload"];
            /**
             * Format: int64
             * @description Server-side updated_at in epoch milliseconds
             */
            updatedAt: number;
            /** Format: int64 */
            syncCursor: number;
            /**
             * Format: int64
             * @description Tombstone marker in epoch milliseconds; null means not deleted
             */
            deletedAt?: number | null;
        };
        PushConflict: {
            /** Format: uuid */
            clientOpId: string;
            /** @enum {string} */
            reason: "stale" | "notFound" | "forbidden";
            serverVersion: components["schemas"]["EntitySnapshot"];
        };
        PushError: {
            /** Format: uuid */
            clientOpId: string;
            /** @enum {string} */
            reason: "validation" | "unknown";
            message: string;
        };
        PullResponse: {
            /** Format: int64 */
            cursor: number;
            changes: components["schemas"]["PullChange"][];
        };
        PushRequest: {
            operations: components["schemas"]["PushOperation"][];
        };
        PushResponse: {
            /** Format: int64 */
            cursor: number;
            applied: string[];
            conflicts: components["schemas"]["PushConflict"][];
            errors: components["schemas"]["PushError"][];
        };
        PhotoUploadUrlRequest: {
            /** Format: uuid */
            photoId: string;
            contentType: string;
        };
        PhotoUploadUrlResponse: {
            /** Format: uri */
            uploadUrl: string;
            /** @enum {string} */
            method: "PUT";
            headers: {
                [key: string]: string;
            };
            /**
             * Format: int64
             * @description Expiry time in epoch milliseconds
             */
            expiresAt: number;
        };
        ErrorResponse: {
            message: string;
        };
    };
    responses: {
        /** @description Unauthorized */
        Unauthorized: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorResponse"];
            };
        };
    };
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    health: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthResponse"];
                };
            };
        };
    };
    signIn: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SignInRequest"];
            };
        };
        responses: {
            /** @description Tokens issued */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TokenPair"];
                };
            };
            401: components["responses"]["Unauthorized"];
        };
    };
    refreshToken: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RefreshRequest"];
            };
        };
        responses: {
            /** @description New token pair */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TokenPair"];
                };
            };
            401: components["responses"]["Unauthorized"];
        };
    };
    syncPull: {
        parameters: {
            query?: {
                /** @description Server cursor from previous pull (0 for first pull) */
                since?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Delta changes */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PullResponse"];
                };
            };
            401: components["responses"]["Unauthorized"];
        };
    };
    syncPush: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PushRequest"];
            };
        };
        responses: {
            /** @description Partial-success push result */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PushResponse"];
                };
            };
            401: components["responses"]["Unauthorized"];
        };
    };
    getPhotoUploadUrl: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PhotoUploadUrlRequest"];
            };
        };
        responses: {
            /** @description Pre-signed upload URL */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PhotoUploadUrlResponse"];
                };
            };
            401: components["responses"]["Unauthorized"];
        };
    };
}
