// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Photo struct {
	ID          string             `json:"id"`
	PhotoableID string             `json:"photoable_id"`
	RemoteUrl   *string            `json:"remote_url"`
	ContentType string             `json:"content_type"`
	Name        *string            `json:"name"`
	Caption     *string            `json:"caption"`
	TakenAt     pgtype.Timestamptz `json:"taken_at"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
	DeletedAt   pgtype.Timestamptz `json:"deleted_at"`
	SyncCursor  int64              `json:"sync_cursor"`
}

type Photoable struct {
	ID        string `json:"id"`
	OwnerType string `json:"owner_type"`
	OwnerID   string `json:"owner_id"`
}

type Plan struct {
	ID          string             `json:"id"`
	ProjectID   string             `json:"project_id"`
	Name        string             `json:"name"`
	PayloadJson []byte             `json:"payload_json"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
	DeletedAt   pgtype.Timestamptz `json:"deleted_at"`
	SyncCursor  int64              `json:"sync_cursor"`
}

type Project struct {
	ID           string             `json:"id"`
	WorkspaceID  string             `json:"workspace_id"`
	Name         string             `json:"name"`
	Address      *string            `json:"address"`
	Description  *string            `json:"description"`
	IsArchived   bool               `json:"is_archived"`
	IsFavourite  bool               `json:"is_favourite"`
	CoverPhotoID *string            `json:"cover_photo_id"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	UpdatedAt    pgtype.Timestamptz `json:"updated_at"`
	DeletedAt    pgtype.Timestamptz `json:"deleted_at"`
	SyncCursor   int64              `json:"sync_cursor"`
}

type RefreshToken struct {
	ID        string             `json:"id"`
	UserID    string             `json:"user_id"`
	TokenHash string             `json:"token_hash"`
	ExpiresAt pgtype.Timestamptz `json:"expires_at"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type Room struct {
	ID         string             `json:"id"`
	PlanID     string             `json:"plan_id"`
	Name       *string            `json:"name"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
	UpdatedAt  pgtype.Timestamptz `json:"updated_at"`
	DeletedAt  pgtype.Timestamptz `json:"deleted_at"`
	SyncCursor int64              `json:"sync_cursor"`
}

type User struct {
	ID           string             `json:"id"`
	Name         string             `json:"name"`
	Email        string             `json:"email"`
	PasswordHash string             `json:"password_hash"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	UpdatedAt    pgtype.Timestamptz `json:"updated_at"`
}

type Wall struct {
	ID         string             `json:"id"`
	RoomID     string             `json:"room_id"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
	UpdatedAt  pgtype.Timestamptz `json:"updated_at"`
	DeletedAt  pgtype.Timestamptz `json:"deleted_at"`
	SyncCursor int64              `json:"sync_cursor"`
}

type Workspace struct {
	ID         string             `json:"id"`
	Name       string             `json:"name"`
	OwnerID    string             `json:"owner_id"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
	UpdatedAt  pgtype.Timestamptz `json:"updated_at"`
	DeletedAt  pgtype.Timestamptz `json:"deleted_at"`
	SyncCursor int64              `json:"sync_cursor"`
}
