// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: photoables.sql

package db

import (
	"context"
)

const createPhotoable = `-- name: CreatePhotoable :one
INSERT INTO photoables (id, owner_type, owner_id)
VALUES ($1, $2, $3)
RETURNING id, owner_type, owner_id
`

type CreatePhotoableParams struct {
	ID        string `json:"id"`
	OwnerType string `json:"owner_type"`
	OwnerID   string `json:"owner_id"`
}

func (q *Queries) CreatePhotoable(ctx context.Context, arg CreatePhotoableParams) (Photoable, error) {
	row := q.db.QueryRow(ctx, createPhotoable, arg.ID, arg.OwnerType, arg.OwnerID)
	var i Photoable
	err := row.Scan(&i.ID, &i.OwnerType, &i.OwnerID)
	return i, err
}

const getPhotoableByID = `-- name: GetPhotoableByID :one
SELECT id, owner_type, owner_id FROM photoables WHERE id = $1 LIMIT 1
`

func (q *Queries) GetPhotoableByID(ctx context.Context, id string) (Photoable, error) {
	row := q.db.QueryRow(ctx, getPhotoableByID, id)
	var i Photoable
	err := row.Scan(&i.ID, &i.OwnerType, &i.OwnerID)
	return i, err
}

const getPhotoableByOwner = `-- name: GetPhotoableByOwner :one
SELECT id, owner_type, owner_id FROM photoables WHERE owner_type = $1 AND owner_id = $2 LIMIT 1
`

type GetPhotoableByOwnerParams struct {
	OwnerType string `json:"owner_type"`
	OwnerID   string `json:"owner_id"`
}

func (q *Queries) GetPhotoableByOwner(ctx context.Context, arg GetPhotoableByOwnerParams) (Photoable, error) {
	row := q.db.QueryRow(ctx, getPhotoableByOwner, arg.OwnerType, arg.OwnerID)
	var i Photoable
	err := row.Scan(&i.ID, &i.OwnerType, &i.OwnerID)
	return i, err
}
