// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: photos.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getPhotoByID = `-- name: GetPhotoByID :one
SELECT id, photoable_id, remote_url, content_type, name, caption, taken_at, created_at, updated_at, deleted_at, sync_cursor FROM photos WHERE id = $1 LIMIT 1
`

func (q *Queries) GetPhotoByID(ctx context.Context, id string) (Photo, error) {
	row := q.db.QueryRow(ctx, getPhotoByID, id)
	var i Photo
	err := row.Scan(
		&i.ID,
		&i.PhotoableID,
		&i.RemoteUrl,
		&i.ContentType,
		&i.Name,
		&i.Caption,
		&i.TakenAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.SyncCursor,
	)
	return i, err
}

const listPhotosSince = `-- name: ListPhotosSince :many
SELECT p.id, p.photoable_id, p.remote_url, p.content_type, p.name, p.caption, p.taken_at, p.created_at, p.updated_at, p.deleted_at, p.sync_cursor FROM photos p
JOIN photoables pa ON p.photoable_id = pa.id
JOIN projects proj ON pa.owner_type = 'project' AND pa.owner_id = proj.id
WHERE proj.workspace_id = $1 AND p.sync_cursor > $2
UNION ALL
SELECT p.id, p.photoable_id, p.remote_url, p.content_type, p.name, p.caption, p.taken_at, p.created_at, p.updated_at, p.deleted_at, p.sync_cursor FROM photos p
JOIN photoables pa ON p.photoable_id = pa.id
JOIN rooms r ON pa.owner_type = 'room' AND pa.owner_id = r.id
JOIN plans pl ON r.plan_id = pl.id
JOIN projects proj ON pl.project_id = proj.id
WHERE proj.workspace_id = $1 AND p.sync_cursor > $2
UNION ALL
SELECT p.id, p.photoable_id, p.remote_url, p.content_type, p.name, p.caption, p.taken_at, p.created_at, p.updated_at, p.deleted_at, p.sync_cursor FROM photos p
JOIN photoables pa ON p.photoable_id = pa.id
JOIN walls w ON pa.owner_type = 'wall' AND pa.owner_id = w.id
JOIN rooms r ON w.room_id = r.id
JOIN plans pl ON r.plan_id = pl.id
JOIN projects proj ON pl.project_id = proj.id
WHERE proj.workspace_id = $1 AND p.sync_cursor > $2
ORDER BY sync_cursor
`

type ListPhotosSinceParams struct {
	WorkspaceID string `json:"workspace_id"`
	SyncCursor  int64  `json:"sync_cursor"`
}

func (q *Queries) ListPhotosSince(ctx context.Context, arg ListPhotosSinceParams) ([]Photo, error) {
	rows, err := q.db.Query(ctx, listPhotosSince, arg.WorkspaceID, arg.SyncCursor)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Photo{}
	for rows.Next() {
		var i Photo
		if err := rows.Scan(
			&i.ID,
			&i.PhotoableID,
			&i.RemoteUrl,
			&i.ContentType,
			&i.Name,
			&i.Caption,
			&i.TakenAt,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
			&i.SyncCursor,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setPhotoRemoteURL = `-- name: SetPhotoRemoteURL :exec
UPDATE photos SET remote_url = $2 WHERE id = $1
`

type SetPhotoRemoteURLParams struct {
	ID        string  `json:"id"`
	RemoteUrl *string `json:"remote_url"`
}

func (q *Queries) SetPhotoRemoteURL(ctx context.Context, arg SetPhotoRemoteURLParams) error {
	_, err := q.db.Exec(ctx, setPhotoRemoteURL, arg.ID, arg.RemoteUrl)
	return err
}

const softDeletePhoto = `-- name: SoftDeletePhoto :one
UPDATE photos SET deleted_at = now(), updated_at = $2 WHERE id = $1 RETURNING id, photoable_id, remote_url, content_type, name, caption, taken_at, created_at, updated_at, deleted_at, sync_cursor
`

type SoftDeletePhotoParams struct {
	ID        string             `json:"id"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) SoftDeletePhoto(ctx context.Context, arg SoftDeletePhotoParams) (Photo, error) {
	row := q.db.QueryRow(ctx, softDeletePhoto, arg.ID, arg.UpdatedAt)
	var i Photo
	err := row.Scan(
		&i.ID,
		&i.PhotoableID,
		&i.RemoteUrl,
		&i.ContentType,
		&i.Name,
		&i.Caption,
		&i.TakenAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.SyncCursor,
	)
	return i, err
}

const upsertPhoto = `-- name: UpsertPhoto :one
INSERT INTO photos (id, photoable_id, content_type, name, caption, taken_at, updated_at)
VALUES ($1, $2, $3, $4, $5, $6, $7)
ON CONFLICT (id) DO UPDATE SET
    photoable_id = EXCLUDED.photoable_id,
    content_type = EXCLUDED.content_type,
    name         = EXCLUDED.name,
    caption      = EXCLUDED.caption,
    taken_at     = EXCLUDED.taken_at,
    updated_at   = EXCLUDED.updated_at,
    deleted_at   = NULL
RETURNING id, photoable_id, remote_url, content_type, name, caption, taken_at, created_at, updated_at, deleted_at, sync_cursor
`

type UpsertPhotoParams struct {
	ID          string             `json:"id"`
	PhotoableID string             `json:"photoable_id"`
	ContentType string             `json:"content_type"`
	Name        *string            `json:"name"`
	Caption     *string            `json:"caption"`
	TakenAt     pgtype.Timestamptz `json:"taken_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) UpsertPhoto(ctx context.Context, arg UpsertPhotoParams) (Photo, error) {
	row := q.db.QueryRow(ctx, upsertPhoto,
		arg.ID,
		arg.PhotoableID,
		arg.ContentType,
		arg.Name,
		arg.Caption,
		arg.TakenAt,
		arg.UpdatedAt,
	)
	var i Photo
	err := row.Scan(
		&i.ID,
		&i.PhotoableID,
		&i.RemoteUrl,
		&i.ContentType,
		&i.Name,
		&i.Caption,
		&i.TakenAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.SyncCursor,
	)
	return i, err
}
