// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: plans.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getPlanByID = `-- name: GetPlanByID :one
SELECT id, project_id, name, payload_json, created_at, updated_at, deleted_at, sync_cursor FROM plans WHERE id = $1 LIMIT 1
`

func (q *Queries) GetPlanByID(ctx context.Context, id string) (Plan, error) {
	row := q.db.QueryRow(ctx, getPlanByID, id)
	var i Plan
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Name,
		&i.PayloadJson,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.SyncCursor,
	)
	return i, err
}

const listPlansSince = `-- name: ListPlansSince :many
SELECT plans.id, plans.project_id, plans.name, plans.payload_json, plans.created_at, plans.updated_at, plans.deleted_at, plans.sync_cursor FROM plans
JOIN projects ON plans.project_id = projects.id
WHERE projects.workspace_id = $1 AND plans.sync_cursor > $2
ORDER BY plans.sync_cursor
`

type ListPlansSinceParams struct {
	WorkspaceID string `json:"workspace_id"`
	SyncCursor  int64  `json:"sync_cursor"`
}

func (q *Queries) ListPlansSince(ctx context.Context, arg ListPlansSinceParams) ([]Plan, error) {
	rows, err := q.db.Query(ctx, listPlansSince, arg.WorkspaceID, arg.SyncCursor)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Plan{}
	for rows.Next() {
		var i Plan
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.Name,
			&i.PayloadJson,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
			&i.SyncCursor,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const softDeletePlan = `-- name: SoftDeletePlan :one
UPDATE plans SET deleted_at = now(), updated_at = $2 WHERE id = $1 RETURNING id, project_id, name, payload_json, created_at, updated_at, deleted_at, sync_cursor
`

type SoftDeletePlanParams struct {
	ID        string             `json:"id"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) SoftDeletePlan(ctx context.Context, arg SoftDeletePlanParams) (Plan, error) {
	row := q.db.QueryRow(ctx, softDeletePlan, arg.ID, arg.UpdatedAt)
	var i Plan
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Name,
		&i.PayloadJson,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.SyncCursor,
	)
	return i, err
}

const upsertPlan = `-- name: UpsertPlan :one
INSERT INTO plans (id, project_id, name, payload_json, updated_at)
VALUES ($1, $2, $3, $4, $5)
ON CONFLICT (id) DO UPDATE SET
    name         = EXCLUDED.name,
    payload_json = EXCLUDED.payload_json,
    updated_at   = EXCLUDED.updated_at,
    deleted_at   = NULL
RETURNING id, project_id, name, payload_json, created_at, updated_at, deleted_at, sync_cursor
`

type UpsertPlanParams struct {
	ID          string             `json:"id"`
	ProjectID   string             `json:"project_id"`
	Name        string             `json:"name"`
	PayloadJson []byte             `json:"payload_json"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) UpsertPlan(ctx context.Context, arg UpsertPlanParams) (Plan, error) {
	row := q.db.QueryRow(ctx, upsertPlan,
		arg.ID,
		arg.ProjectID,
		arg.Name,
		arg.PayloadJson,
		arg.UpdatedAt,
	)
	var i Plan
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Name,
		&i.PayloadJson,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.SyncCursor,
	)
	return i, err
}
