// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: projects.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getProjectByID = `-- name: GetProjectByID :one
SELECT id, workspace_id, name, address, description, is_archived, is_favourite, cover_photo_id, created_at, updated_at, deleted_at, sync_cursor FROM projects WHERE id = $1 LIMIT 1
`

func (q *Queries) GetProjectByID(ctx context.Context, id string) (Project, error) {
	row := q.db.QueryRow(ctx, getProjectByID, id)
	var i Project
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.Name,
		&i.Address,
		&i.Description,
		&i.IsArchived,
		&i.IsFavourite,
		&i.CoverPhotoID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.SyncCursor,
	)
	return i, err
}

const listProjectsSince = `-- name: ListProjectsSince :many
SELECT id, workspace_id, name, address, description, is_archived, is_favourite, cover_photo_id, created_at, updated_at, deleted_at, sync_cursor FROM projects
WHERE workspace_id = $1 AND sync_cursor > $2
ORDER BY sync_cursor
`

type ListProjectsSinceParams struct {
	WorkspaceID string `json:"workspace_id"`
	SyncCursor  int64  `json:"sync_cursor"`
}

func (q *Queries) ListProjectsSince(ctx context.Context, arg ListProjectsSinceParams) ([]Project, error) {
	rows, err := q.db.Query(ctx, listProjectsSince, arg.WorkspaceID, arg.SyncCursor)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Project{}
	for rows.Next() {
		var i Project
		if err := rows.Scan(
			&i.ID,
			&i.WorkspaceID,
			&i.Name,
			&i.Address,
			&i.Description,
			&i.IsArchived,
			&i.IsFavourite,
			&i.CoverPhotoID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
			&i.SyncCursor,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const softDeleteProject = `-- name: SoftDeleteProject :one
UPDATE projects SET deleted_at = now(), updated_at = $2 WHERE id = $1 RETURNING id, workspace_id, name, address, description, is_archived, is_favourite, cover_photo_id, created_at, updated_at, deleted_at, sync_cursor
`

type SoftDeleteProjectParams struct {
	ID        string             `json:"id"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) SoftDeleteProject(ctx context.Context, arg SoftDeleteProjectParams) (Project, error) {
	row := q.db.QueryRow(ctx, softDeleteProject, arg.ID, arg.UpdatedAt)
	var i Project
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.Name,
		&i.Address,
		&i.Description,
		&i.IsArchived,
		&i.IsFavourite,
		&i.CoverPhotoID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.SyncCursor,
	)
	return i, err
}

const upsertProject = `-- name: UpsertProject :one
INSERT INTO projects (id, workspace_id, name, address, description, is_archived, is_favourite, updated_at)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
ON CONFLICT (id) DO UPDATE SET
    name         = EXCLUDED.name,
    address      = EXCLUDED.address,
    description  = EXCLUDED.description,
    is_archived  = EXCLUDED.is_archived,
    is_favourite = EXCLUDED.is_favourite,
    updated_at   = EXCLUDED.updated_at,
    deleted_at   = NULL
RETURNING id, workspace_id, name, address, description, is_archived, is_favourite, cover_photo_id, created_at, updated_at, deleted_at, sync_cursor
`

type UpsertProjectParams struct {
	ID          string             `json:"id"`
	WorkspaceID string             `json:"workspace_id"`
	Name        string             `json:"name"`
	Address     *string            `json:"address"`
	Description *string            `json:"description"`
	IsArchived  bool               `json:"is_archived"`
	IsFavourite bool               `json:"is_favourite"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) UpsertProject(ctx context.Context, arg UpsertProjectParams) (Project, error) {
	row := q.db.QueryRow(ctx, upsertProject,
		arg.ID,
		arg.WorkspaceID,
		arg.Name,
		arg.Address,
		arg.Description,
		arg.IsArchived,
		arg.IsFavourite,
		arg.UpdatedAt,
	)
	var i Project
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.Name,
		&i.Address,
		&i.Description,
		&i.IsArchived,
		&i.IsFavourite,
		&i.CoverPhotoID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.SyncCursor,
	)
	return i, err
}
