// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"context"
)

type Querier interface {
	CreatePhotoable(ctx context.Context, arg CreatePhotoableParams) (Photoable, error)
	CreateRefreshToken(ctx context.Context, arg CreateRefreshTokenParams) error
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	CreateWorkspace(ctx context.Context, arg CreateWorkspaceParams) (Workspace, error)
	DeleteRefreshToken(ctx context.Context, id string) error
	GetPhotoByID(ctx context.Context, id string) (Photo, error)
	GetPhotoableByID(ctx context.Context, id string) (Photoable, error)
	GetPhotoableByOwner(ctx context.Context, arg GetPhotoableByOwnerParams) (Photoable, error)
	GetPlanByID(ctx context.Context, id string) (Plan, error)
	GetProjectByID(ctx context.Context, id string) (Project, error)
	GetRefreshTokenByHash(ctx context.Context, tokenHash string) (RefreshToken, error)
	GetRefreshTokenByHashForUpdate(ctx context.Context, tokenHash string) (RefreshToken, error)
	GetRoomByID(ctx context.Context, id string) (Room, error)
	GetUserByEmail(ctx context.Context, email string) (User, error)
	GetUserByID(ctx context.Context, id string) (User, error)
	GetWallByID(ctx context.Context, id string) (Wall, error)
	GetWorkspaceByID(ctx context.Context, id string) (Workspace, error)
	GetWorkspaceByOwnerID(ctx context.Context, ownerID string) (Workspace, error)
	ListPhotosSince(ctx context.Context, arg ListPhotosSinceParams) ([]ListPhotosSinceRow, error)
	ListPlansSince(ctx context.Context, arg ListPlansSinceParams) ([]Plan, error)
	ListProjectsSince(ctx context.Context, arg ListProjectsSinceParams) ([]Project, error)
	ListRoomsSince(ctx context.Context, arg ListRoomsSinceParams) ([]Room, error)
	ListWallsSince(ctx context.Context, arg ListWallsSinceParams) ([]Wall, error)
	SetPhotoRemoteURL(ctx context.Context, arg SetPhotoRemoteURLParams) error
	SoftDeletePhoto(ctx context.Context, arg SoftDeletePhotoParams) (Photo, error)
	SoftDeletePlan(ctx context.Context, arg SoftDeletePlanParams) (Plan, error)
	SoftDeleteProject(ctx context.Context, arg SoftDeleteProjectParams) (Project, error)
	SoftDeleteRoom(ctx context.Context, arg SoftDeleteRoomParams) (Room, error)
	SoftDeleteWall(ctx context.Context, arg SoftDeleteWallParams) (Wall, error)
	UpsertPhoto(ctx context.Context, arg UpsertPhotoParams) (Photo, error)
	UpsertPhotoableByOwner(ctx context.Context, arg UpsertPhotoableByOwnerParams) (Photoable, error)
	UpsertPlan(ctx context.Context, arg UpsertPlanParams) (Plan, error)
	UpsertProject(ctx context.Context, arg UpsertProjectParams) (Project, error)
	UpsertRoom(ctx context.Context, arg UpsertRoomParams) (Room, error)
	UpsertWall(ctx context.Context, arg UpsertWallParams) (Wall, error)
}

var _ Querier = (*Queries)(nil)
