// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: rooms.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getRoomByID = `-- name: GetRoomByID :one
SELECT id, plan_id, name, created_at, updated_at, deleted_at, sync_cursor FROM rooms WHERE id = $1 LIMIT 1
`

func (q *Queries) GetRoomByID(ctx context.Context, id string) (Room, error) {
	row := q.db.QueryRow(ctx, getRoomByID, id)
	var i Room
	err := row.Scan(
		&i.ID,
		&i.PlanID,
		&i.Name,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.SyncCursor,
	)
	return i, err
}

const listRoomsSince = `-- name: ListRoomsSince :many
SELECT rooms.id, rooms.plan_id, rooms.name, rooms.created_at, rooms.updated_at, rooms.deleted_at, rooms.sync_cursor FROM rooms
JOIN plans ON rooms.plan_id = plans.id
JOIN projects ON plans.project_id = projects.id
WHERE projects.workspace_id = $1 AND rooms.sync_cursor > $2
ORDER BY rooms.sync_cursor
`

type ListRoomsSinceParams struct {
	WorkspaceID string `json:"workspace_id"`
	SyncCursor  int64  `json:"sync_cursor"`
}

func (q *Queries) ListRoomsSince(ctx context.Context, arg ListRoomsSinceParams) ([]Room, error) {
	rows, err := q.db.Query(ctx, listRoomsSince, arg.WorkspaceID, arg.SyncCursor)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Room{}
	for rows.Next() {
		var i Room
		if err := rows.Scan(
			&i.ID,
			&i.PlanID,
			&i.Name,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
			&i.SyncCursor,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const softDeleteRoom = `-- name: SoftDeleteRoom :one
UPDATE rooms SET deleted_at = now(), updated_at = $2 WHERE id = $1 RETURNING id, plan_id, name, created_at, updated_at, deleted_at, sync_cursor
`

type SoftDeleteRoomParams struct {
	ID        string             `json:"id"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) SoftDeleteRoom(ctx context.Context, arg SoftDeleteRoomParams) (Room, error) {
	row := q.db.QueryRow(ctx, softDeleteRoom, arg.ID, arg.UpdatedAt)
	var i Room
	err := row.Scan(
		&i.ID,
		&i.PlanID,
		&i.Name,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.SyncCursor,
	)
	return i, err
}

const upsertRoom = `-- name: UpsertRoom :one
INSERT INTO rooms (id, plan_id, name, updated_at)
VALUES ($1, $2, $3, $4)
ON CONFLICT (id) DO UPDATE SET
    name       = EXCLUDED.name,
    updated_at = EXCLUDED.updated_at,
    deleted_at = NULL
RETURNING id, plan_id, name, created_at, updated_at, deleted_at, sync_cursor
`

type UpsertRoomParams struct {
	ID        string             `json:"id"`
	PlanID    string             `json:"plan_id"`
	Name      *string            `json:"name"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) UpsertRoom(ctx context.Context, arg UpsertRoomParams) (Room, error) {
	row := q.db.QueryRow(ctx, upsertRoom,
		arg.ID,
		arg.PlanID,
		arg.Name,
		arg.UpdatedAt,
	)
	var i Room
	err := row.Scan(
		&i.ID,
		&i.PlanID,
		&i.Name,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.SyncCursor,
	)
	return i, err
}
