// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: walls.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getWallByID = `-- name: GetWallByID :one
SELECT id, room_id, created_at, updated_at, deleted_at, sync_cursor FROM walls WHERE id = $1 LIMIT 1
`

func (q *Queries) GetWallByID(ctx context.Context, id string) (Wall, error) {
	row := q.db.QueryRow(ctx, getWallByID, id)
	var i Wall
	err := row.Scan(
		&i.ID,
		&i.RoomID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.SyncCursor,
	)
	return i, err
}

const listWallsSince = `-- name: ListWallsSince :many
SELECT walls.id, walls.room_id, walls.created_at, walls.updated_at, walls.deleted_at, walls.sync_cursor FROM walls
JOIN rooms ON walls.room_id = rooms.id
JOIN plans ON rooms.plan_id = plans.id
JOIN projects ON plans.project_id = projects.id
WHERE projects.workspace_id = $1 AND walls.sync_cursor > $2
ORDER BY walls.sync_cursor
`

type ListWallsSinceParams struct {
	WorkspaceID string `json:"workspace_id"`
	SyncCursor  int64  `json:"sync_cursor"`
}

func (q *Queries) ListWallsSince(ctx context.Context, arg ListWallsSinceParams) ([]Wall, error) {
	rows, err := q.db.Query(ctx, listWallsSince, arg.WorkspaceID, arg.SyncCursor)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Wall{}
	for rows.Next() {
		var i Wall
		if err := rows.Scan(
			&i.ID,
			&i.RoomID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
			&i.SyncCursor,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const softDeleteWall = `-- name: SoftDeleteWall :one
UPDATE walls SET deleted_at = now(), updated_at = $2 WHERE id = $1 RETURNING id, room_id, created_at, updated_at, deleted_at, sync_cursor
`

type SoftDeleteWallParams struct {
	ID        string             `json:"id"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) SoftDeleteWall(ctx context.Context, arg SoftDeleteWallParams) (Wall, error) {
	row := q.db.QueryRow(ctx, softDeleteWall, arg.ID, arg.UpdatedAt)
	var i Wall
	err := row.Scan(
		&i.ID,
		&i.RoomID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.SyncCursor,
	)
	return i, err
}

const upsertWall = `-- name: UpsertWall :one
INSERT INTO walls (id, room_id, updated_at)
VALUES ($1, $2, $3)
ON CONFLICT (id) DO UPDATE SET
    updated_at = EXCLUDED.updated_at,
    deleted_at = NULL
RETURNING id, room_id, created_at, updated_at, deleted_at, sync_cursor
`

type UpsertWallParams struct {
	ID        string             `json:"id"`
	RoomID    string             `json:"room_id"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) UpsertWall(ctx context.Context, arg UpsertWallParams) (Wall, error) {
	row := q.db.QueryRow(ctx, upsertWall, arg.ID, arg.RoomID, arg.UpdatedAt)
	var i Wall
	err := row.Scan(
		&i.ID,
		&i.RoomID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.SyncCursor,
	)
	return i, err
}
